version: "3.8"

services:
  php:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/
    ports:
      - "80:80"

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345678
    ports:
      - '5432:5432'

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
    volumes:
      - mongodb:/etc/mongo
    ports:
      - "27017:27017"

  caddy:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
    # Uncomment the following line to enable the development mode
    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    ports:
      - "88:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  mailer:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    #    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis:/data

volumes:
  symfony:
  mysql:
  postgres:
  mongodb:
  caddy_data:
  caddy_config:
  redis:
