version: "3.8"

services:
  php:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/
    ports:
      - "80:80"

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql:
